### ISSUE TITLE
How to deploy on github page?

### ISSUE THREAD

**Issue by drorata** [eggcaker/jekyll-org#12]
The plugin works as expected on the local site, but when I push it to github (username.github.io) it doesn't work. 

The local installation is using `submodules`. At first, github complained about the URL of the submodule, but after fixing it it seemed to be in place correctly. In particular, `username.github.io/_plugins` contains the sub-directory named `jekyll-org`.

Is there anything further that I have to set? Can it work or is it that github doesn't support the plugin?

**Comment by eggcaker** [comment]
just because github page don't allow the custom plugins. so, you should: 
1. create another branch for example  `source` ,   keep all your jekyll source  including the _plugins stuff. 
2. create a new directory (ex: `_site`)  to hold the generated source, add a remote to your master branch. ignore this directory from .gitignore 
3. use jekyll to build website int to `_site` , then go to `_site` , push all generated files to your remote master branch.

you can try that ,  if you really need some deploy script  let me know.

**Comment by drorata** [comment]
So basically you mean that I should have two repositories? On for the sources which would be synced to some remote  and the other of the build which would be synced with drorata.github.io? In this case I would guess that push hooks should be used, right?

**Comment by mashdot** [comment]
Personally I have a master branch where I installed jekyll. Then I have a `Rakefile` which I use to publish to the `gh-pages` branch.

I originally was inspired by https://github.com/ixti/ixti.github.io/blob/source/Rakefile from http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html which are worth a read.

For a manual method and a useful read: http://24ways.org/2013/get-started-with-github-pages/

**Comment by drorata** [comment]
This sounds like to much work. At the moment the scale of my blog is limited and I can live with markdown. I guess... :-1:

**Comment by eggcaker** [comment]
sure , for the basic blog things, markdown enough. ;)
