### ISSUE TITLE
Feature request: org-mode properties rather than YAML frontmatter for regular pages as well as posts

### ISSUE THREAD

**Issue by stig** [eggcaker/jekyll-org#16]
As per the discussion here: https://github.com/eggcaker/jekyll-org/pull/15#issuecomment-209243646

I would love to use org-mode properties rather than YAML frontmatter for regular pages as well, e.g. something like

``` org
#+LAYOUT: post
#+TITLE:  Welcome to Jekyll with orgmode!

this is my page's content
```

rather than:

``` org

---
layout: post
title: Welcome to Jekyll with orgmode!

---

this is my page's content
```

**Comment by njayinthehouse** [comment]
If this is an open issue, why is it stated that this is possible in the README? 
(Followed the instructions in the README, to my dismay it didn't work.)

**Comment by eggcaker** [comment]
it only working with posts  not pages

**Comment by MoHKale** [comment]
To clarify, I believe this issue is two fold:
* Firstly, jekyll treats any file that doesn't have a YAML header as a static file. This behaviour doesn't apply to Post files because they've got their own special method for being read (implemented in `jekyll/readers/post_reader.rb`).
* Issue #37 addresses this point as well. Any org file outside of the posts directory won't be converted to HTML unless it has a YAML header. 

In our situation if an org file doesn't have a YAML header the file will be treated as a StaticFile and won't end up having a Document instance made. In our current code base, all the conversion logic for org files is in the Document class so it doesn't end up being converted. So the solution is to make jekyll create Document instances for org files, even when they don't have YAML headers. This might be kind of messy, but it should work :).

**Comment by MoHKale** [comment]
Okay, I've managed to get conversion to HTML supported for org files in collections other than_ posts. A major improvement 😄 if I do say so myself ~~(to help my ego justify why it took an entire day to do this & only 10 lines of code 😢😨😫)~~.

**Comment by eggcaker** [comment]
the converter merged and released.  working now, Thanks @MoHKale

**Comment by MoHKale** [comment]
no problem, I hope there weren't any issues.
