### ISSUE TITLE
tags not beings parsed correctly

### ISSUE THREAD

**Issue by lbgaml** [eggcaker/jekyll-org#33]
When I specify tags according to the documentation

#+TAGS: foo bar

I get an error thrown with two different themes I have tried ([next theme](https://github.com/Simpleyyt/jekyll-theme-next) and [beautiful Jekyll](https://github.com/daattali/beautiful-jekyll)). The error is:

> Liquid Exception: undefined method `each' for "foo, bar":String in tags.html

I'm new to Jekyll, so I might be missing something obvious, but any help would be appreciated.

**Comment by bzg** [comment]
Hi @lbgaml ! Can you try to use `#+TAGS: foo bar` without any comma between `foo` and `bar` ?

**Comment by lbgaml** [comment]
Hi @bzg, thanks for the quick response. I get the same error:

> Liquid Exception: undefined method `each' for "foo bar":String in tags.html

This also happens if I try "#+TAGS: [foo, bar]"

**Comment by bzg** [comment]
Can you try by testing [org-ruby](https://github.com/wallyqs/org-ruby) directly?

**Comment by lbgaml** [comment]
If I call the following on the file:

>org-ruby --translate html

It only returns the title (as <h1 class="title">) and then the body of the post. There is no output for the #+layout: or #+tags: headers.

**Comment by bzg** [comment]
Sorry, I can't help you debugging this right now. I hope someone will jump in.

**Comment by lbgaml** [comment]
Okay, @bzg thanks for the initial pointers.

**Comment by pseudomyne** [comment]
Hi, @lbgaml, have you found any workarounds ? I get a similar issue when trying to put [multiple  #tags](https://github.com/eggcaker/jekyll-org/issues/40).

**Comment by l3kn** [comment]
I've gone through the code for `org-ruby`,
`in_buffer_settings` are parsed with the regex

```ruby
InBufferSettingRegexp = /^#\+(\w+):\s*(.*)$/
```

where the first capture group is used as option name
and the second one as option value.
There seems to be no additional parsing.

No matter the variant (`#+TAGS: foo bar`, `#+TAGS: [foo, bar]`, ...),
the tags will be passed from `org-ruby` to `jekyll-org` as a string.

My suggestion would be to modify `jekyll-org`
so that the `TAGS` value is parsed into a list,
possibly with support for tags containing spaces
e.g. `#+TAGS: "with spaces" foo bar`.

The easiest way to do this seems to be
```ruby
require ‘csv’
CSV::parse_line(tags_string, ’ ')
```
(instead of just `tags_string.split(' ')` to handle quoted tags with spaces).

I'll try this out in a fork and open a pull request.
