### ISSUE TITLE
Is it a requirement that we place .org files in the _posts folder?

### ISSUE THREAD

**Issue by oystersauce8** [eggcaker/jekyll-org#37]
I've been using a custom collection, instead of `_posts/`, say `_custom1/`
but this gem doesn't seem to work on `_custom1/`

So, is it a requirement that we place .org files in the _posts folder?

**Comment by MoHKale** [comment]
Hmmmm... I'm facing the same issue. Not really sure why. I could swear it was working fine just a short while ago.

**Comment by MoHKale** [comment]
I think I've found where the issue is. it's here [here](https://github.com/jekyll/jekyll/blob/master/lib/jekyll/collection.rb#L57). Looks like the read method looks for a YAML header in the files and only creates a Document from them when there is one; otherwise it'll just treat it as a static file and copy it over as is :(. 

I believe if you add

```
---
---
```

as the first two lines of your org files, jekyll will discover them... but seeing as `jekyll-org` completely disregards the contents of this block (you specify such things using org variables), doing so is both ugly and meaningless. We'll have to work on this.
