### ISSUE TITLE
<div class="highlight"> not being attached to src blocks

### ISSUE THREAD

**Issue by castle-bravo** [eggcaker/jekyll-org#41]
For example:
```
#+BEGIN_SRC python
print("hello world")
#+END_SRC
```
In the _site folder, the html shows up as:
```
<pre class="src" lang="python">
print(&quot;hello world&quot;)
</pre>
```
When I invoke `org-ruby` from the command-line, I get:
```
$ org-ruby ./test.org 
<div class="highlight"><pre><span></span><span class="k">print</span><span class="p">(</span><span class="s2">&quot;hello world&quot;</span><span class="p">)</span>
</pre></div>
```
Which appropriately wraps my code in a highlight div.
I think it has something do do with the yaml file that's passed to the orgmode parser on line 52 of jekyll-org.rb, though I'm not completely sure. I'm totally new to ruby, so I'm having a little trouble pinning down the cause.

**Comment by MoHKale** [comment]
You can configure this, however the implementation is upto the [org-ruby](https://github.com/bdewey/org-ruby) gem. As it stands, they do offer support for syntax highlighting with `pygments` and I've opened an [issue](https://github.com/bdewey/org-ruby/issues/79) for syntax highlighting through rouge.

Seeing as I personally use rouge, I'll wait for them to add support for rouge before implementing support on this gem. If someone else would like to get the ball rolling and add support for pygments right now; that would be much appreciated :)

**Comment by jlevers** [comment]
I'm interested in taking on adding support for `pygments` so that I can use this gem for code blocks that need syntax highlighting...I haven't worked on a Ruby project in a very long time, so if anyone is able to offer some pointers for where I should start looking, I would appreciate that.

I read through a fair bit of `org-ruby`'s code, and I'm not clear on why anything needs to be done to `jekyll-org`'s code to support `pygments`, since `org-ruby` does all the parsing. I assume I'm just misunderstanding something.

**Comment by mohkale** [comment]
@jlevers I didn't really look into it all that strongly but you're correct, I don't think there's much we'll need to do. In truth, all you need to do is read the users config.yml file (already done by jekyll), find the pygments section (or create some sane defaults for it) and then pass that along to the org-mode parser.

**Comment by jlevers** [comment]
It turned out that all I needed to do was to `bundle install pygments.rb`, and then add a CSS file with the styles for syntax highlighting. `org-ruby` auto-detects `pygments`, so there's really nothing you have to do to make it work.

The theme I'm using happened to include a SCSS file that recognized the `pygments` classes already, so I didn't actually have to add a CSS file, but CSS files for a number of different syntax highlighting themes is [here](https://github.com/richleland/pygments-css).

**Comment by jlevers** [comment]
I thought this might not resolve the issue cleanly enough to be worth a PR, but since you said so...done!
